/**
 * @description       : 
 * @author            : Pranav Narayan
 * @group             : 
 * @last modified on  : 08-26-2024
 * @last modified by  : Pranav Narayan 
 * Modifications Log
 * Ver   Date         Author           Modification
 * 1.0   08-26-2024   Pranav Narayan   Initial Version
**/
public with sharing class cls_Controller {
    public cls_Controller() {
        system.debug('Constructor');
    }
}