/**
 * @description       : 
 * @author            : Pranav Narayan
 * @group             : 
 * @last modified on  : 08-26-2024
 * @last modified by  : Pranav Narayan 
 * Modifications Log
 * Ver   Date         Author           Modification
 * 1.0   08-26-2024   Pranav Narayan   Initial Version
**/
@isTest
public with sharing class test_cls_Controller {
    
    @isTest
    private static void testTestCase() {
        // Test data setup
    
        // Actual test
        Test.startTest();
            cls_Controller instance = new cls_Controller();
        Test.stopTest();
    
        // Asserts
    }
}